apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: appmesh-gateway
bases:
  - ../base/appmesh-gateway
resources:
- namespace.yaml
patchesStrategicMerge:
  - deployment.yaml
  - service.yaml
